version: "3"
services:
  node: 
    image: mynodecourseapi
    command : npm start
    ports: 
    - "5000:5051"
    depends_on:
      - mongo
    environment:
       MONGO_PORT: 27017
       MONGO_DB: course
       MONGO_HOSTNAME: mongo
    deploy:
      mode: replicated
      replicas: 2
    networks: 
      - courseAPI_network
  mongo: 
    image: mongo:latest
    networks: 
      - courseAPI_network
    volumes: 
      - dbdata:/data/db
    environment: 
      MONGO_INITDB_DATABASE: course
networks:
  courseAPI_network:
volumes:
  dbdata: