version: "3"
services:
  node: 
    build: .
    command : npm start
    ports: 
    - "5000:5051"
  mongo: 
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes: 
      - '/data/courseDB'
  mongo-express: 
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongo

