const MONGO_PORT=27017;
const MONGO_DB="course";
const MONGO_HOSTNAME="mongo";
const MONGO_USERNAME= "root";
const MONGO_PASSWORD = "root";
module.exports = {MONGO_PORT, MONGO_DB, MONGO_HOSTNAME,MONGO_USERNAME,MONGO_PASSWORD};